const sizes = [35,36,37,38,39,40,41,42,43,44,45];
const data = [
    {
      img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
      title: "Nike Air Monarch IV",
      bestseller: "true" ,
      reviews: "(123 reviews)",
      prevPrice: "$240,00",
      newPrice: "200",
      company: "Nike",
      color: "white",
      category: "sneakers",
      size: 1 && 2 && 3,
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
      title: "Nike Air Vapormax Plus",
      bestseller: "true" ,
      reviews: "(123 reviews)",
      prevPrice: "$210,00",
      newPrice: "200",
      company: "Nike",
      color: "red",
      category: "sneakers",
      size: '',
      count: 1,
    },
  
    {
      img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
      title: "Nike Waffle One Sneaker",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$245,00",
      newPrice: "200",
      company: "Nike",
      color: "green",
      category: "sneakers",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
      title: "Adidas Running Shoe",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$235,00",
      newPrice: "200",
      company: "Adidas",
      color: "black",
      category: "sneakers",
      size: '',
      count: 1,
    },
 
    {
      img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
      title: "Knit Ballet Flat",
      bestseller: "true" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Adidas",
      color: "black",
      category: "flats",
      size: '',
      count: 1,
    },
  
    {
      img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
      title: "Loafer Flats",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Vans",
      color: "white",
      category: "flats",
      size: '',
      count: 1,
    },
  
    {
      img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
      title: "Nike Zoom Freak",
      bestseller: "true" ,
      reviews: "(123 reviews)",
      prevPrice: "$220,00",
      newPrice: "200",
      company: "Nike",
      color: "green",
      category: "sneakers",
      size: '',
      count: 1,
    },
  
    {
      img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
      title: "Adidas Men's Sneaker",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$220,00",
      newPrice: "200",
      company: "Adidas",
      color: "blue",
      category: "sneakers",
      size: '',
      count: 1,
    },
  
    {
      img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
      title: "Adidas Men's Sneaker",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$220,00",
      newPrice: "200",
      company: "Adidas",
      color: "blue",
      category: "sneakers",
      size: '',
      count: 1,
    },
  
    {
      img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
      title: "Adidas Men's Sneaker",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$220,00",
      newPrice: "200",
      company: "Adidas",
      color: "blue",
      category: "sneakers",
      size: '',
      count: 1,
    },
  
    {
      img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
      title: "Adidas Men's Sneaker",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$220,00",
      newPrice: "200",
      company: "Adidas",
      color: "blue",
      category: "sneakers",
      size: '',
      count: 1,
    },
  
    {
      img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
      title: "PUMA BLACK-OCE",
      bestseller: "true" ,
      reviews: "(123 reviews)",
      prevPrice: "$195,00",
      newPrice: "150",
      company: "Puma",
      color: "green",
      category: "sneakers",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
      title: "Pacer Future Sneaker",
      bestseller: "true" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Puma",
      color: "red",
      category: "sneakers",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
      title: "Unisex-Adult Super",
      bestseller: "true" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Puma",
      color: "black",
      category: "sneakers",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
      title: "Roma Basic Sneaker",
      bestseller: "true" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Puma",
      color: "white",
      category: "sneakers",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
      title: "Pacer Future Doubleknit",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Puma",
      color: "black",
      category: "sneakers",
      size: '',
      count: 1,
    },
  
    {
      img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
      title: "Fusion Evo Golf Shoe",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "100",
      company: "Puma",
      color: "green",
      category: "sneakers",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
      title: "Rainbow Chex Skate",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "100",
      company: "Vans",
      color: "red",
      category: "flats",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
      title: "Low-Top Trainers",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "100",
      company: "Vans",
      color: "white",
      category: "sandals",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
      title: "Vans Unisex Low-Top",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "100",
      company: "Vans",
      color: "blue",
      category: "sandals",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
      title: "Classic Bandana Sneakers",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Nike",
      color: "black",
      category: "sandals",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
      title: "Chunky High Heel",
      bestseller: "true" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Vans",
      color: "black",
      category: "heels",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
      title: "Slip On Stiletto High Heel",
      bestseller: "true" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "100",
      company: "Puma",
      color: "black",
      category: "heels",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
      title: "DREAM PAIRS Court Shoes",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Nike",
      color: "red",
      category: "heels",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
      title: "Nike Air Vapormax Plus",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Nike",
      color: "red",
      category: "sneakers",
      size: '',
      count: 1,
    },
  
    {
      img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
      title: "Low Mid Block Heels",
      bestseller: "true" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "200",
      company: "Nike",
      color: "black",
      category: "heels",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
      title: "Chunky High Heel",
      bestseller: "true" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Adidas",
      color: "black",
      category: "heels",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
      title: "Amore Fashion Stilettos",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "150",
      company: "Adidas",
      color: "white",
      category: "heels",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
      title: "Bridal Sandals Glitter",
      bestseller: "false" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Adidas",
      color: "black",
      category: "heels",
      size: '',
      count: 1,
    },
    {
      img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
      title: "Wedding Prom Bridal",
      bestseller: "true" ,
      reviews: "(123 reviews)",
      prevPrice: "$140,00",
      newPrice: "50",
      company: "Adidas",
      color: "black",
      category: "flats",
      size: '',
      count: 1,
    },
    {
      img: "https://i.ibb.co/7VdH0W2/pngwing-com.png",
      title: "Adidas Superstar Originals Shoe",
      bestseller: "true" ,
      reviews: "(268 reviews)",
      prevPrice: "$150,00",
      newPrice: "99",
      company: "Adidas",
      color: "white",
      category: "sneakers",
      size: '',
      count: 1,
    }
  ];
  
  export default data;